### ISSUE TITLE
<feed> nodes in XML output causing validation issue at Google Web Tools

### ISSUE THREAD

**Issue by erzahurak** [furzeface/grunt-xml-sitemap#9]
if I leave in the <feed> nodes, validation of the sitemap fails on Google Web Tools.  If i remove them, all works fine.  Have you seen the same thing?

**Comment by arminrosu** [comment]
This will do it:

Update tasks/xml_sitemap.js#L51:

```js
var urlset = builder.create('urlset')
			.att('xmlns', 'http://www.sitemaps.org/schemas/sitemap/0.9')
			.att('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')
			.att('xsi:schemaLocation', 'http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd');
```

tasks/xml_sitemap.js#L70
```js
var xmlString = urlset.end({
```

And don't forget to remove the now redundant `var feed = ...` declaration.

**Comment by DinosaurDad** [comment]
Thanks for this fix!

**Comment by ctruelson** [comment]
Created a pull request for this https://github.com/furzeface/grunt-xml-sitemap/pull/10
